# These are supported funding model platforms

patreon: CosmicJesterX

tidelift: Linear.app

community_bridge: cloud-foundry

lfx_crowdfunding: cloud-foundry

github: https://github.com/CosmicJesterX
